---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-training-app
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-training-back
  namespace: devops-training-app
  labels:
    app: web
spec:
  selector:
    matchLabels:        
      app: devops-training-back
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: devops-training-back          
    spec:
      hostNetwork: true
      containers:
      - name: devops-training-back
        image: davargonez/devops_training:backend_#{version}#
        ports:
        - name: appbackport
          containerPort: 3000
          protocol: TCP          
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: devops-training-back-svc
  namespace: devops-training-app
spec:
  ports:
  - port: 3000
  selector:
    app:  devops-training-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-training-front
  namespace: devops-training-app
  labels:
    app: web
spec:
  selector:
    matchLabels:        
      app: devops-training-front
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: devops-training-front          
    spec:
      hostNetwork: true
      containers:
      - name: devops-training-front
        image: davargonez/devops_training:frontend_#{version}#
        ports:
        - name: appfrontport
          containerPort: 4200
          protocol: TCP          
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: devops-training-front-svc
  namespace: devops-training-app
spec:
  type: LoadBalancer
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    app:  devops-training-front