apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstraining
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
        octopusexport: OctopusExport
    spec:
      containers:
        - name: backend
          image: 'devops_training:backEnd_18'
          ports:
            - name: backendport
              containerPort: 3000
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
