apiVersion: v1
kind: Service
metadata:
  name: devopstrainingservice
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  clusterIP: 10.0.0.12
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 52.149.190.127    