apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsTraining
  labels:
    app: frontEnd
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontEnd
        octopusexport: OctopusExport
    spec:
      containers:
        - name: frontend
          image: 'devops_training:frontend_18'
          ports:
            - name: appfrontport
              containerPort: 4200
              protocol: TCP
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
